- import_playbook: clean_receiver_daq.config.yml

- name: clean daq machine from daq software
  hosts: '{{ host }}'
  become: true
  tasks:
    - name: remove daq software
      shell: |
          rm -rf /home/dbe/git /home/dbe/miniconda3 /home/dbe/service_scripts /home/dbe/bin /home/dbe/.condarc
